name: Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'your local repo branch'
        required: true
        default: 22.03
        type: choice
        options:
        - master
        - 22.03
        - 21.02

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [bcm53xx-generic, rockchip-armv8, sunxi-cortexa53, x86-64]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Init build dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        ./scripts/00_init.sh build_env

    - name: Clone OpenWrt
      run: |
        ./scripts/00_init.sh openwrt

    - name: Get variable
      working-directory: ./openwrt
      id: var
      run: |
        case ${{ github.event.inputs.branch }} in
          master)
            _release_tag=snapshot-r$(date +%g.%j)
            _prerelease=true
            ;;
          22.03)
            _release_tag=$(git tag --sort=taggerdate --list 'v22.*' | tail -1)
            git checkout $_release_tag
            _prerelease=false
            ;;
          21.02)
            _release_tag=$(git tag --sort=taggerdate --list 'v21.*' | tail -1)
            git checkout $_release_tag
            _prerelease=false
            ;;
          *)
            echo "Can't get local/upstream's branch/tags"
            ;;
        esac
        case ${{ matrix.target }} in
          bcm53xx-generic)  _device=k3                ;;
          rockchip-armv8)   _device=r2c-r2s           ;;
          sunxi-cortexa53)  _device=nanopi-neo2       ;;
          x86-64)           _device=x86-64            ;;
          *)                echo "wrong devices"      ;;
        esac
        _artifact=${{ matrix.target }}
        _artifact_path=openwrt/bin/targets/${_artifact/-//}
        echo "release_tag=$_release_tag" >> $GITHUB_OUTPUT
        echo "prerelease=$_prerelease" >> $GITHUB_OUTPUT
        echo "device=$_device" >> $GITHUB_OUTPUT
        echo "artifact=$_artifact_path" >> $GITHUB_OUTPUT

    - name: Fetch Other repos
      run: |
        ./scripts/00_init.sh other-repos

    - name: Feeds update & install
      run: |
        ./scripts/00_init.sh feeds

    - name: Customize Packages
      working-directory: ./openwrt
      run: |
        cp -L ../scripts/${{ steps.var.outputs.device }}_customization.sh .
        cp ../scripts/01_customize_packages.sh .
        /bin/bash ${{ steps.var.outputs.device }}_customization.sh

    - name: Convert Translation
      working-directory: ./openwrt
      run: |
        cp ../scripts/02_convert_translation.sh .
        /bin/bash 02_convert_translation.sh

    - name: Add ACL
      working-directory: ./openwrt
      run: |
        cp ../scripts/03_create_acl_for_luci.sh .
        /bin/bash 03_create_acl_for_luci.sh -a

    - name: Get cache toolchain
      uses: HiGarfield/cachewrtbuild@main
      with:
        prefix: ${{ github.workspace }}/openwrt
        mixkey: ${{ matrix.target }}

    - name: Make Config
      working-directory: ./openwrt
      run: |
        cp ../config/${{ steps.var.outputs.device }}_defconfig .config
        make defconfig

    - name: Make Download
      working-directory: ./openwrt
      run: |
        make download -j`nproc`

    - name: Compile OpenWrt
      working-directory: ./openwrt
      run: |
        make -j`nproc` || make -j1 V=s

    - name: Assemble Artifact
      run: |
        ls ${{ steps.var.outputs.artifact }}
        cat ${{ steps.var.outputs.artifact }}/config.buildinfo
        rm -rf ${{ steps.var.outputs.artifact }}/{packages,*.buildinfo,*.json,*.manifest,*kernel.bin,*-rootfs.*,sha256sums}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.var.outputs.release_tag }}
        path: ${{ steps.var.outputs.artifact }}/*

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        target_commitish: ${{ github.event.inputs.branch }}
        prerelease: ${{ steps.var.outputs.prerelease }}
        tag_name: ${{ steps.var.outputs.release_tag }}
        files: ${{ steps.var.outputs.artifact }}/*
